language: android
android:
  components:
    - extra-android-m2repository
    - extra-google-m2repository
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.2
    - android-25

  script:
     - ./gradlew build connectedCheck