language: android
sudo: false
jdk: oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository

script: './gradlew build check'

deploy:
  provider: releases
  api_key: 9fc271e6ff2965f3aaf1fcb77dd92cdef0b1ad6a
  file: app/build/outputs/aar/app-release.aar
  skip_cleanup: true
  on:
    repo: brunordg/ctanywhere
    tags: true