language: android
android:
  jdk:
    - oraclejdk7
  components:
    - build-tools-25.0.2
    - android-25
    - sys-img-armeabi-v7a-android-tv-l
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  script:
    - ./gradlew assembleRelease